# About Me

Here is more information about our members!

## Brizesh


## Brandon Hi

I grew up in Northville, Michigan and have spent most of my life there. However, I spent two years of high school in Dallas, Texas. Growing up, I played several sports and in high school I played golf and hockey.
Currently, I am a graduate student at The University of Michigan - Ross School of Business studying Business Analytics. I chose to pursue this degree in hopes of landing a job in the field of sports analytics. I love watching the NBA and the NFL (as well as college basketball and football) and I took a few analytics and ML classes in my undergrad that opened my eyes to the power and promise of AI.

Even though it is early in the program, I can already say that I have genuinely enjoyed everyone I have met so far. This is a talented group that I believe will do wonderful things.

Previous Education
I graduated from my BBA program this spring, also at The Ross School of Business. I loved my undergraduate education and the experience that came with it. I find that the professors at The Ross School of Business are of the highest quality.

## Yulin


## Andrew

## Yidan

Hello, my name is Yidan Gu, a current MBAn student from Ross School of Business.I love dealing with numbers such as different kinds of math problems so I chose accounting as my undergraduate major in the University of Illinois, Urbana-Champaign. However, during my undergraduate study, my related experience really helped me to clarify my ultimate passion: analytics, especially business analytics, which combines my professional knowledge in the business field and more practical knowledge in the data field. To enrich my understanding, I have taken several analytical courses, interned in Amazon and completed a data certificate in UCLA. Finally, I was successfully admitted by Ross, which is the most valuable experience in my life I believe. After classes, I have joined several student organizations, including the International Consulting Network, Accounting Club of UIUC and Overseas China Educational Foundation. I really enjoyed those activities such as doing real-world consulting projects, fundraising events and so on. In my spare time, I love watching movies, listening to music, traveling and shopping. Oh! One interesting fun fact about me is that I have a super cute cat. 