# Our Learnings from the Term {#Scope}

## How did we use the class material to make our group more effective?

Overall, we believe that all stages in our group project work smoothly with the help of class materials. At first, in the beginning stage, we established team charter to guide future works based on the course readings, such as the discipline of teams, building company’s vision and mission, and the effect of a team charter. Additionally, we apply the related concepts for group decision making and receiving & seeking feedbacks to topic and content selections. For instance, since we meet all the requirements for making group decision, we set up several meetings aimed to formulate the structure for our project’s content. Then, during each meeting, the guidelines for making and receiving feedbacks really helps us to improve the efficiency of communications. Lastly, the assigned reading: Agile Analytics Book is beneficial in distributing tasks to group members, increasing working efficiency in group and enhancing collaborations. To illustrate, that book contains many principles and guidelines which are essential to be used in an effective working environment. 

## How did our group handle challenges and changes?

During the execution of the project, we encountered many changes and challenges. Although those challenges increased the difficulty of finishing the project, we solved all of them successfully. This is because we followed the below principles during our collaboration: 1. Always plan ahead. We always discuss the internal deadline immediately after a new assignment is issued and decide how we should divide the work by people and by steps to complete it. By keeping this habit, we always leave a time buffer so that we can respond to changes in time. 2. Shared responsibility. When faced with each challenge, we will share the workload, and play our unique strengths. Our workload is not exactly equal in each individual task, but overall, we are all actively involved. 3. Collaborate with a purpose. Our group's style is very straightforward because we are very result-oriented and value the purpose of each collaboration. This allows us to avoid wasting any team meeting, and every meeting has a clear deliverable.

## How did we divide work, leveraged unique strengths of each individual in the team?

Our group discussed the strengths of each member when we created the team chatter, such as who was good at technical skills, who was good at presentation, who was good at writing, etc. This gave each of us a unique role in the group and allowed us to maximize our value. In each assignment, we will also divide the work according to such strengths. After the first one or two assignments, we got to know more about our respective characteristics, and we also built up more trust, so our cooperation gradually went more smoothly as a result.

## How did we adopt agile work practices?

Some agile work practices we adopted was making sure that we wanted to satisfy the customer with out product. In this class, most of the time, the customers were Sanjeev and Jeff, as they were the ones who were grading our work. We tried to check in with them to make sure that we were on the right track. For example, when drafting our team charter, we first drafted an original document and then showed it to Jeff to get some feedback. We then took that feedback into consideration and made our final changes before turning it in. 
Another practice we adopted was trying to meet face to face more. We wanted to this because it would be much easier for information to flow between group members. For example when Brizesh was showing the rest of the team how to setup git and use R, it wouldn’t have had the same benefit if he did it over zoom. Instead, the learning process was much faster because we were able to meet face to face.
We also tried adopting agile work practices by meeting more regularly and often. We wanted to make sure communication was at a high level and to do that, we needed to meet more. However, we would always try to keep the meetings short, so that we were not wasting any time. We made sure to communicate any conflicts and so far all team members have been accomodating, which also helps our team’s chemistry.

## How did we manage the RMarkdown/Git/GitHub complexity and learning curve?

At the beginning of the term, only Brizesh was experienced in R or GitHub. Thankfully, he was able to teach us how to set up our repository and push our content. Our approach was to learn by working as a group. Everyone watched Brizesh show us the way, and then we all helped each other replicate the process of pulling, committing, and pushing. Our goal was to make sure nobody got left behind and that everyone was comfortable with doing this process on their own by the end of the term. At first, we were hesitant to pull and push outside of our in-person meetings, but by the end of the term, we were very comfortable with the whole process thanks to repetition and collaboration. 
I believe that one of our most important resources was our team culture of open communication and willingness to teach each other (and to learn from each other). Since most of us were doing this for the first time, it was vital that we felt comfortable asking each other for help. While RStudio was definitely overwhelming at first, we leveraged the expert in our group to take the lead for the initial work involving R and GitHub. We credit this success to our organic team structure which allowed different members to take the lead based on the subject-matter, rather than operating through a strict hierarchy. Overall, the learning curve is not so bad as long as the team is willing to put in the reps and willing to ask each other for help.

## What more could we do to become a more effective and productive team in the time left?

While we believe our team is trending in the right direction, there is always room for improvement.  As busy as all the team members are at this time in the academic term, it is important to take 10-15 minutes and discuss ways in which the group can be more effective and productive.  No doubt this is a generic answer to the question but far too often, whether in college or in the workforce, individuals and teams become myopically focused on simply completing the multitude of tasks currently assigned when this is exactly the time to take a step back, evaluate current processes, and brainstorm ways to improve efficiency.
More specifically, The Team The Team The Team has so far completed most of its work at team meetings.  While this was an effective way to conduct our business earlier in the academic term, it usually required a one hour time block.  With so many competing interests (other MBAn courses, networking, internships, etc.) during our remaining time, it has been hard to identify additional time during the week (outside of our normally scheduled Monday meetings) in which all five members of The Team The Team The Team can meet for an hour.  The Team The Team The Team will adopt a new hybrid meeting structure (somewhere between a formal meeting and a standup) in which the meeting begins with specially stating the goals of the meeting, each team member’s product is then reviewed and feedback provided, new scope analyzed and discussed, and closes with team members individually briefing the group on their assigned tasks to ensure comprehension.


