# Cultural Differences {#team4}

## Chronemics

The study of how time affects communication.  It is used to understand the use of time in differing cultures.  Some cultures see time as something concrete and linear, while other cultures see time as something rather relative and cyclic.  The former perspective on time was termed by Edward T. Hall as monochronic and the latter as polychronic.

## Proxemics

Proxemics is the interpretation of spatial relationships within the context of cultural normalities and psychosocial factors.  The interpretation of these relationships determines the dynamics of human interaction and reaction to their surroundings.  Proxemics is the act of betraying affiliations through the dynamics of proximity.  This occurs at the unconscious, subconscious, and conscious levels.  Additionally, proxemics is the proximity or distance to and from other people and is based upon physiological, sociological, and physical principles.  Proxemics may be categorized as relative distance, proxemics push or pull distance.

## Direct vs. Indirect

There is a spectrum of formality throughout the cultures of the world, with some cultures being direct and explicit.  Others cultures are less direct and more ambiguous.  The theory of cross-cultural communication styles is extensive, but for our purpose we will focus on the distinction between direct and indirect communication styles.  

